name: Lint Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Python linter
        run: |
          find ./server -name "*.py" -exec flake8 {} +
          echo "Linted all python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run JavaScript linter
        run: |
          find ./server/database -name "*.js" -exec jshint {} +
          echo "Linted all js files successfully"
